### ISSUE TITLE
Update GitHub Wiki Documentation

### ISSUE THREAD

**Issue by Aricky3** [cse110-fa22-group31/cse110-fa22-group31#15]
### User Story
Professors and developers need documentation for how to use features.

### Tasks
- [ ] Table of Contents
- [ ] Basic features for users of program
- [ ] Function info for developers

**Comment by thomasrexin** [comment]
added set up guide to wiki on project page
