### ISSUE TITLE
List of categories for feedback

### ISSUE THREAD

**Issue by kungharrison** [cse110-fa22-group31/cse110-fa22-group31#20]
## User Story
As a professor, I want to sort all my notes based on categories of my choice.

➡️**The list of categories should be customizable and unique for each course.**
> The professor is teaching course A and course B this quarter.
> Course A has categories [exam] [lecture] [assignment]
> Course B has categories [midterm1] [midterm2] [lecture]

➡️**Each course should have a default set of categories (just in case the professor is too lazy to customize some themselves)**
➡️**A list of categories is shown when writing a note.**
➡️**Each note must have at least one category before posting. One note can have multiple categories.**
➡️**On the overview page, there should be a dropdown menu for selecting the category of the notes that will be shown.**

## Tasks
- [x] Might need a separate storage system to store all category tags
    - [x] When the web app loads, the default set of categories is populated to the storage system
- [x] Add functionality for customizing categories 
- [x] Add functionality of assigning categories to notes
    - [x] Each category should have a button (defined by HTML and styled by CSS)
    - [x] When clicked, the category is then linked to the note
- [x] Add functionality of showing notes based on categories

![Image](https://user-images.githubusercontent.com/53415491/203373427-87335097-cbed-4dbd-8ea2-39fcef6b7935.png)
