### ISSUE TITLE
Add Unit Testing & E2E Testing

### ISSUE THREAD

**Issue by HoldenA1** [cse110-fa22-group31/cse110-fa22-group31#24]
### User Story
As a developer, I want to ensure the code works well and is tested regularly with pull requests using GitHub actions.
### Tasks
- [ ] write unit tests to test some basic usages
- [x] implement unite tests into GitHub actions
- [x] Add E2E Testing to make sure the web page is functioning as desired
