### ISSUE TITLE
Change Classes

### ISSUE THREAD

**Issue by kungharrison** [cse110-fa22-group31/cse110-fa22-group31#28]
### User Story
This is part of the functionality of the html site. Loads in a list of classes that a professor teaches throughout the year (visible to students). Suggestions should be categorized based on course numbers so the professor and students can choose to view suggestions for a specific course.

### Tasks
- [ ] Create database for professor classes
- [ ] Work on studentfeedbackview.html and professorfeedbackview.html
- [x] Categorize suggestions
    - [x] Group suggestions based on course numbers
    - [ ] Implement the function of only showing a set of suggestions when a course number is chosen

### Wireframe
[Link to miro](https://miro.com/app/board/uXjVPG5rCMw=/)

![Image](https://user-images.githubusercontent.com/53415491/203373464-cdfb7e4e-ad98-47b9-b882-851d71d7a000.png)
