### ISSUE TITLE
CI Pipeline

### ISSUE THREAD

**Issue by kungharrison** [cse110-fa22-group31/cse110-fa22-group31#31]
### User Story
Developers need a CI/CD pipeline that should be run as Github Actions. We are using some simple experimental code to demonstrate testing, docs, linting, etc.  Given the parallel creation of devops features as you code we are considering making feature branches to test out the pipeline, then once finalized have it work on main and stage branches appropriately.

CI/CD pipeline phase 1 should be a vetting phase with:
1. linting and code style enforcement (may happen in pipeline and/or in editor)
2. code quality via tool  (ex. Codeclimate, Codacy, etc.)
3. code quality via human review (ex. Pull Requests)
4. unit tests via automation (ex. Jest, Tape, Ava, Cypress, Mocha/Chai, etc.)*
5. documentation generation via automation (ex. JSDocs)

### Tasks
For the satisfactory completion of this phase you should provide the following items and store them in your repo under /admin/cipipeline.
- [x] phase1.png - a diagram of your phase 1 build pipeline (can be phase1.drawio.png if using draw.io)
- [x] phase1.md - a short 2 page (roughly) status on the pipeline in terms of what is currently functional (and what is planned or in progress). Embed your diagram in the markdown file.
- [x] phase1.mp4 - a no more than 2 min video demonstration of the pipeline

### Info
canvas.ucsd.edu/courses/39754/assignments/526058

**Comment by kungharrison** [comment]
@number000000 Do you think you can work on writing out the design documents for our CI pipeline which is due?
