### ISSUE TITLE
Bug Tracker

### ISSUE THREAD

**Issue by kungharrison** [cse110-fa22-group31/cse110-fa22-group31#75]
### User Story
Users should see no bugs when navigating the site.

### Tasks
- [x] View_feedback returns to student_view, sometimes it needs to return to professor_view
- [x] Authentication will go into negative attempts
- [x] currClass keeps resetting everytime a student go back and view feedback again
- [x] View_feedback for student does not work. Cannot view comment.
