### ISSUE TITLE
Add, delete, and view suggestion buttons interaction with Javascript

### ISSUE THREAD

**Issue by kungharrison** [cse110-fa22-group31/cse110-fa22-group31#8]
### User Story
As a professor, I want to be able to easily jot down notes of suggestions I hear from students in class. I should also be able to view all notes I have and delete any of them by my choice. (For now, notes are stored locally)
### Tasks
- [x] add suggestion javascript function *(add to localStorage)*
- [x] delete suggestion javascript function *(delete from localStorage)*
- [x] view suggestion javascript function *(when a note is clicked, a new page should open up with only the selected note shown)*

**Comment by KenKunoo** [comment]
@kungharrison We only need to create the local / notetaking version right? Will we have someone create the HTML layout for us or do we need to create it ourselves?

**Comment by kungharrison** [comment]
@KenKunoo Yeah just the local notetaking version for now, the other group will be doing the HTML layout.
